### ISSUE TITLE
`margin-top` overriden when using just `column-gap` 

### ISSUE THREAD

**Issue by thewilkybarkid** [limitlessloop/flex-gap-polyfill#22]
Using `column-gap` on its own still results in `margin-top` being changed, but _overriden_ to 0 rather than recaluclated.

```css
.something {
  display: flex;
  column-gap: 2rem;
  margin-top: 10px;
}
```

<details>
<summary>Output</summary>

```css
.something {
    display: flex;
    margin-top: 10px;
    --fgp-has-polyfil_gap-container: initial;
    --fgp-gap_container_row: var(--fgp-has-polyfil_gap-container, calc(var(--fgp-gap_parent_row, 0px) - )) !important;
    pointer-events: none;
    --fgp-gap_parent_row: initial;
    --fgp-gap_item_row: initial;
    --fgp-gap_row: var(--fgp-gap_container_row) !important;
    padding-top: 0.02px;
    --fgp-margin-top: calc(var(--fgp-gap_row) + 10px);
    margin-top: var(--fgp-margin-top) !important;
    --fgp-gap_container_column: var(--fgp-has-polyfil_gap-container, calc(var(--fgp-gap_parent_column, 0px) - 2rem)) !important;
    pointer-events: none;
    --fgp-gap_parent_column: initial;
    --fgp-gap_item_column: initial;
    --fgp-gap_column: var(--fgp-gap_container_column) !important;
    padding-top: 0.02px;
    --fgp-margin-right: calc(var(--fgp-gap_column) + 0px);
    margin-right: var(--fgp-margin-right) !important;
}
```

</details>

Both

```css
.something {
  display: flex;
  column-gap: 2rem;
  row-gap: 0;
  margin-top: 10px;
}
```

and

```css
.something {
  display: flex;
  gap: 0 2rem;
  margin-top: 10px;
}
```

work in the the `margin-top` is recalculated correctly, but it's redundant to do so. I'd expect just `margin-right` to change in all these cases, not `margin-top`.
