### ISSUE TITLE
Overriding the margin on one level

### ISSUE THREAD

**Issue by frufrufrufrufru** [limitlessloop/flex-gap-polyfill#34]
If I have 2 (or more) classes at the same level then there is a problem with overriding margin:

So if I have:

```html
<div class="Header Page__header>
  ...
</div>
```

```css
.Header {
  gap: 20px;
  ...
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: space-between;
}

.Page__header {
  margin-top: 60px;
}
```

Then generated margin for `.Header` will overrides `margin-top` from `.Page__header`.

**Comment by limitlessloop** [comment]
Thanks for reporting. This is a shortcoming of the polyfill as it's using CSS alone so it doesn't know what selectors will be used together. A workaround for cases like this is by factoring in the margin that the polyfill creates.

For example:

```
.Page__header {
    margin-top: calc(60px + var(--fgp-margin-top, 0px));
}
```

The next release will provide a better solution to this, although it comes at the cost of more code.

**Comment by frufrufrufrufru** [comment]
I tried this and it doesn't work. Or I am doing something wrong.

`.Page__header` before:

```css
.Page__header {
    margin-top: 60px;
}
```

`margin-top: 60px;` > `margin-top: calc(60px + var(--fgp-margin-top, 0px));`

`.Page__header` after:

```css
.Page__header {
    margin-top: calc(60px + 0px);
    margin-top: calc(60px + var(--fgp-margin-top, 0px));
}
```

![image](https://user-images.githubusercontent.com/83294543/116318283-354f9e80-a7bd-11eb-8072-75d12f8c7d11.png)

**Comment by limitlessloop** [comment]
Ah sorry, the earlier version had to use `!important` to override containers which may be nested, but I have since managed to move this to a custom property so this doesn't happen. Does it work if you do either of these options?

```css
.Page__header {
    margin-top: calc(60px + var(--fgp-margin-top, 0px)) !important;
}

// or

.Page__header.Page__header {
    margin-top: calc(60px + var(--fgp-margin-top, 0px));
}
```
